/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) haique_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {6, 1, 1};

/* haique_expl_ode_fun:(i0[13],i1[10],i2[6])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][10] : 0;
  a02=(a00*a01);
  a03=2.;
  a02=(a02/a03);
  a04=arg[0]? arg[0][5] : 0;
  a05=arg[0]? arg[0][11] : 0;
  a06=(a04*a05);
  a06=(a06/a03);
  a02=(a02+a06);
  a06=arg[0]? arg[0][6] : 0;
  a07=arg[0]? arg[0][12] : 0;
  a08=(a06*a07);
  a08=(a08/a03);
  a02=(a02+a08);
  a02=(-a02);
  if (res[0]!=0) res[0][3]=a02;
  a02=arg[0]? arg[0][3] : 0;
  a08=(a02*a01);
  a08=(a08/a03);
  a09=(a06*a05);
  a09=(a09/a03);
  a08=(a08-a09);
  a09=(a04*a07);
  a09=(a09/a03);
  a08=(a08+a09);
  if (res[0]!=0) res[0][4]=a08;
  a08=(a06*a01);
  a08=(a08/a03);
  a09=(a02*a05);
  a09=(a09/a03);
  a08=(a08+a09);
  a09=(a00*a07);
  a09=(a09/a03);
  a08=(a08-a09);
  if (res[0]!=0) res[0][5]=a08;
  a08=(a00*a05);
  a08=(a08/a03);
  a09=(a04*a01);
  a09=(a09/a03);
  a08=(a08-a09);
  a09=(a02*a07);
  a09=(a09/a03);
  a08=(a08+a09);
  if (res[0]!=0) res[0][6]=a08;
  a08=1.;
  a09=casadi_sq(a04);
  a10=casadi_sq(a06);
  a10=(a09+a10);
  a10=(a03*a10);
  a10=(a08-a10);
  a11=2.6700000000000002e-02;
  a12=arg[1]? arg[1][1] : 0;
  a13=(a11*a12);
  a14=casadi_fabs(a12);
  a13=(a13*a14);
  a15=arg[1]? arg[1][8] : 0;
  a16=-1.0000000000000001e-01;
  a15=(a15+a16);
  a16=sin(a15);
  a17=(a13*a16);
  a18=arg[1]? arg[1][3] : 0;
  a19=(a11*a18);
  a20=casadi_fabs(a18);
  a19=(a19*a20);
  a21=arg[1]? arg[1][9] : 0;
  a22=sin(a21);
  a23=(a19*a22);
  a17=(a17+a23);
  a23=arg[1]? arg[1][5] : 0;
  a24=(a11*a23);
  a25=casadi_fabs(a23);
  a24=(a24*a25);
  a26=(a24*a16);
  a17=(a17+a26);
  a26=arg[1]? arg[1][7] : 0;
  a27=(a11*a26);
  a28=casadi_fabs(a26);
  a27=(a27*a28);
  a29=(a27*a22);
  a17=(a17+a29);
  a10=(a10*a17);
  a29=(a00*a06);
  a30=(a02*a04);
  a31=(a29+a30);
  a31=(a03*a31);
  a32=arg[1]? arg[1][0] : 0;
  a33=(a11*a32);
  a34=casadi_fabs(a32);
  a33=(a33*a34);
  a15=cos(a15);
  a34=(a13*a15);
  a33=(a33+a34);
  a34=arg[1]? arg[1][2] : 0;
  a35=(a11*a34);
  a36=casadi_fabs(a34);
  a35=(a35*a36);
  a33=(a33+a35);
  a21=cos(a21);
  a35=(a19*a21);
  a33=(a33+a35);
  a35=arg[1]? arg[1][4] : 0;
  a36=(a11*a35);
  a37=casadi_fabs(a35);
  a36=(a36*a37);
  a33=(a33+a36);
  a36=(a24*a15);
  a33=(a33+a36);
  a36=arg[1]? arg[1][6] : 0;
  a11=(a11*a36);
  a37=casadi_fabs(a36);
  a11=(a11*a37);
  a33=(a33+a11);
  a11=(a27*a21);
  a33=(a33+a11);
  a31=(a31*a33);
  a10=(a10+a31);
  a31=4.6719999999999997e+00;
  a10=(a10/a31);
  a11=arg[2]? arg[2][0] : 0;
  a11=(a11/a31);
  a10=(a10+a11);
  if (res[0]!=0) res[0][7]=a10;
  a10=(a00*a04);
  a11=(a02*a06);
  a10=(a10+a11);
  a10=(a03*a10);
  a10=(a10*a17);
  a04=(a04*a06);
  a02=(a02*a00);
  a04=(a04-a02);
  a04=(a03*a04);
  a04=(a04*a33);
  a10=(a10+a04);
  a10=(a10/a31);
  a04=arg[2]? arg[2][1] : 0;
  a04=(a04/a31);
  a10=(a10+a04);
  if (res[0]!=0) res[0][8]=a10;
  a29=(a29-a30);
  a29=(a03*a29);
  a29=(a29*a17);
  a00=casadi_sq(a00);
  a00=(a00+a09);
  a03=(a03*a00);
  a08=(a08-a03);
  a08=(a08*a33);
  a29=(a29+a08);
  a29=(a29/a31);
  a08=9.8065999999999995e+00;
  a29=(a29-a08);
  a08=arg[2]? arg[2][2] : 0;
  a08=(a08/a31);
  a29=(a29+a08);
  if (res[0]!=0) res[0][9]=a29;
  a29=3.0249999999999999e-01;
  a13=(a13+a24);
  a24=(a13-a19);
  a24=(a24-a27);
  a29=(a29*a24);
  a24=arg[2]? arg[2][3] : 0;
  a29=(a29+a24);
  a24=1.0222874999999999e-01;
  a08=(a24*a05);
  a08=(a08*a07);
  a29=(a29+a08);
  a08=1.6095641999999999e-01;
  a31=(a08*a05);
  a31=(a31*a07);
  a29=(a29-a31);
  a31=1.0170715000000000e-01;
  a29=(a29/a31);
  if (res[0]!=0) res[0][10]=a29;
  a29=8.0767500000000006e-03;
  a34=casadi_sq(a34);
  a32=casadi_sq(a32);
  a35=casadi_sq(a35);
  a33=(a32+a35);
  a33=(a34-a33);
  a36=casadi_sq(a36);
  a33=(a33+a36);
  a29=(a29*a33);
  a33=arg[2]? arg[2][4] : 0;
  a29=(a29+a33);
  a31=(a31*a01);
  a33=(a31*a07);
  a29=(a29-a33);
  a33=(a08*a01);
  a33=(a33*a07);
  a29=(a29+a33);
  a29=(a29/a24);
  if (res[0]!=0) res[0][11]=a29;
  a29=1.5000000000000000e+00;
  a33=-3.0249999999999999e-01;
  a13=(a13*a16);
  a19=(a19+a27);
  a19=(a19*a22);
  a13=(a13-a19);
  a33=(a33*a13);
  a13=1.1100000000000001e-03;
  a12=(a13*a12);
  a12=(a12*a14);
  a14=-1.1100000000000001e-03;
  a23=(a14*a23);
  a23=(a23*a25);
  a12=(a12+a23);
  a12=(a12*a15);
  a33=(a33+a12);
  a18=(a13*a18);
  a18=(a18*a20);
  a26=(a14*a26);
  a26=(a26*a28);
  a18=(a18+a26);
  a18=(a18*a21);
  a33=(a33+a18);
  a29=(a29*a33);
  a33=2.9999999999999999e-01;
  a32=(a14*a32);
  a14=(a14*a34);
  a32=(a32+a14);
  a35=(a13*a35);
  a32=(a32+a35);
  a13=(a13*a36);
  a32=(a32+a13);
  a33=(a33*a32);
  a29=(a29+a33);
  a33=arg[2]? arg[2][5] : 0;
  a29=(a29+a33);
  a31=(a31*a05);
  a29=(a29+a31);
  a24=(a24*a01);
  a24=(a24*a05);
  a29=(a29-a24);
  a29=(a29/a08);
  if (res[0]!=0) res[0][12]=a29;
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void haique_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void haique_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void haique_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void haique_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int haique_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int haique_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real haique_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* haique_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* haique_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* haique_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* haique_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
