/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) haique_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {6, 1, 1};
static const casadi_int casadi_s3[3] = {23, 1, 1};

/* haique_expl_vde_adj:(i0[13],i1[13],i2[10],i3[6])->(o0[23]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a01=2.;
  a02=2.6700000000000002e-02;
  a03=arg[2]? arg[2][1] : 0;
  a04=(a02*a03);
  a05=casadi_fabs(a03);
  a06=(a04*a05);
  a07=arg[2]? arg[2][8] : 0;
  a08=sin(a07);
  a09=(a06*a08);
  a10=arg[2]? arg[2][3] : 0;
  a11=(a02*a10);
  a12=casadi_fabs(a10);
  a13=(a11*a12);
  a14=arg[2]? arg[2][9] : 0;
  a15=sin(a14);
  a16=(a13*a15);
  a09=(a09+a16);
  a16=arg[2]? arg[2][5] : 0;
  a17=(a02*a16);
  a18=casadi_fabs(a16);
  a19=(a17*a18);
  a20=(a19*a08);
  a09=(a09+a20);
  a20=arg[2]? arg[2][7] : 0;
  a21=(a02*a20);
  a22=casadi_fabs(a20);
  a23=(a21*a22);
  a24=(a23*a15);
  a09=(a09+a24);
  a24=2.1404109589041098e-01;
  a25=arg[1]? arg[1][8] : 0;
  a25=(a24*a25);
  a26=(a09*a25);
  a26=(a01*a26);
  a27=(a00*a26);
  a28=arg[0]? arg[0][5] : 0;
  a29=arg[1]? arg[1][9] : 0;
  a29=(a24*a29);
  a30=(a09*a29);
  a30=(a01*a30);
  a31=(a28*a30);
  a32=arg[0]? arg[0][4] : 0;
  a33=arg[2]? arg[2][0] : 0;
  a34=(a02*a33);
  a35=casadi_fabs(a33);
  a36=(a34*a35);
  a07=cos(a07);
  a37=(a06*a07);
  a36=(a36+a37);
  a37=arg[2]? arg[2][2] : 0;
  a38=(a02*a37);
  a39=casadi_fabs(a37);
  a40=(a38*a39);
  a36=(a36+a40);
  a14=cos(a14);
  a40=(a13*a14);
  a36=(a36+a40);
  a40=arg[2]? arg[2][4] : 0;
  a41=(a02*a40);
  a42=casadi_fabs(a40);
  a43=(a41*a42);
  a36=(a36+a43);
  a43=(a19*a07);
  a36=(a36+a43);
  a43=arg[2]? arg[2][6] : 0;
  a44=(a02*a43);
  a45=casadi_fabs(a43);
  a46=(a44*a45);
  a36=(a36+a46);
  a46=(a23*a14);
  a36=(a36+a46);
  a46=(a36*a25);
  a46=(a01*a46);
  a47=(a32*a46);
  a31=(a31+a47);
  a27=(a27-a31);
  a31=arg[1]? arg[1][7] : 0;
  a24=(a24*a31);
  a31=(a36*a24);
  a31=(a01*a31);
  a47=(a28*a31);
  a27=(a27+a47);
  a47=arg[0]? arg[0][12] : 0;
  a48=5.0000000000000000e-01;
  a49=arg[1]? arg[1][6] : 0;
  a49=(a48*a49);
  a50=(a47*a49);
  a27=(a27+a50);
  a50=arg[0]? arg[0][11] : 0;
  a51=arg[1]? arg[1][5] : 0;
  a51=(a48*a51);
  a52=(a50*a51);
  a27=(a27+a52);
  a52=arg[0]? arg[0][10] : 0;
  a53=arg[1]? arg[1][4] : 0;
  a53=(a48*a53);
  a54=(a52*a53);
  a27=(a27+a54);
  if (res[0]!=0) res[0][3]=a27;
  a27=(a00*a30);
  a54=(a32+a32);
  a36=(a36*a29);
  a36=(a01*a36);
  a54=(a54*a36);
  a27=(a27-a54);
  a54=arg[0]? arg[0][3] : 0;
  a55=(a54*a46);
  a27=(a27-a55);
  a55=(a28*a26);
  a27=(a27+a55);
  a55=(a00*a31);
  a27=(a27+a55);
  a55=(a50*a49);
  a27=(a27+a55);
  a55=(a47*a51);
  a27=(a27-a55);
  a55=arg[1]? arg[1][3] : 0;
  a48=(a48*a55);
  a55=(a52*a48);
  a27=(a27-a55);
  if (res[0]!=0) res[0][4]=a27;
  a27=(a00*a46);
  a55=(a28+a28);
  a36=(a55*a36);
  a56=(a54*a30);
  a36=(a36+a56);
  a27=(a27-a36);
  a36=(a32*a26);
  a27=(a27+a36);
  a36=(a54*a31);
  a27=(a27+a36);
  a09=(a09*a24);
  a09=(a01*a09);
  a55=(a55*a09);
  a27=(a27-a55);
  a55=(a52*a49);
  a27=(a27-a55);
  a55=(a47*a53);
  a27=(a27+a55);
  a55=(a50*a48);
  a27=(a27-a55);
  if (res[0]!=0) res[0][5]=a27;
  a30=(a32*a30);
  a46=(a28*a46);
  a30=(a30+a46);
  a26=(a54*a26);
  a30=(a30+a26);
  a31=(a32*a31);
  a30=(a30+a31);
  a31=(a00+a00);
  a31=(a31*a09);
  a30=(a30-a31);
  a31=(a52*a51);
  a30=(a30+a31);
  a31=(a50*a53);
  a30=(a30-a31);
  a31=(a47*a48);
  a30=(a30-a31);
  if (res[0]!=0) res[0][6]=a30;
  a30=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][7]=a30;
  a30=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][8]=a30;
  a30=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][9]=a30;
  a30=1.0170715000000000e-01;
  a31=6.2128618417333090e+00;
  a09=arg[1]? arg[1][12] : 0;
  a31=(a31*a09);
  a09=(a50*a31);
  a26=(a30*a09);
  a46=1.0222874999999999e-01;
  a09=(a46*a09);
  a26=(a26-a09);
  a09=1.6095641999999999e-01;
  a27=9.7819840309110706e+00;
  a55=arg[1]? arg[1][11] : 0;
  a27=(a27*a55);
  a55=(a47*a27);
  a36=(a09*a55);
  a26=(a26+a36);
  a55=(a30*a55);
  a26=(a26-a55);
  a55=(a28*a49);
  a26=(a26-a55);
  a55=(a00*a51);
  a26=(a26+a55);
  a55=(a54*a53);
  a26=(a26+a55);
  a55=(a32*a48);
  a26=(a26-a55);
  if (res[0]!=0) res[0][10]=a26;
  a30=(a30*a52);
  a26=(a30*a31);
  a55=(a46*a52);
  a55=(a55*a31);
  a26=(a26-a55);
  a55=9.8321504437003693e+00;
  a36=arg[1]? arg[1][10] : 0;
  a55=(a55*a36);
  a47=(a47*a55);
  a36=(a09*a47);
  a26=(a26-a36);
  a47=(a46*a47);
  a26=(a26+a47);
  a47=(a32*a49);
  a26=(a26+a47);
  a47=(a54*a51);
  a26=(a26+a47);
  a47=(a00*a53);
  a26=(a26-a47);
  a47=(a28*a48);
  a26=(a26-a47);
  if (res[0]!=0) res[0][11]=a26;
  a52=(a09*a52);
  a52=(a52*a27);
  a30=(a30*a27);
  a52=(a52-a30);
  a09=(a09*a50);
  a09=(a09*a55);
  a52=(a52-a09);
  a46=(a46*a50);
  a46=(a46*a55);
  a52=(a52+a46);
  a49=(a54*a49);
  a52=(a52+a49);
  a51=(a32*a51);
  a52=(a52-a51);
  a53=(a28*a53);
  a52=(a52+a53);
  a48=(a00*a48);
  a52=(a52-a48);
  if (res[0]!=0) res[0][12]=a52;
  a52=(a33+a33);
  a48=-1.1100000000000001e-03;
  a53=2.9999999999999999e-01;
  a53=(a53*a31);
  a51=(a48*a53);
  a49=(a52*a51);
  a46=8.0767500000000006e-03;
  a27=(a46*a27);
  a52=(a52*a27);
  a49=(a49-a52);
  a33=casadi_sign(a33);
  a52=1.;
  a50=casadi_sq(a32);
  a09=casadi_sq(a28);
  a50=(a50+a09);
  a50=(a01*a50);
  a50=(a52-a50);
  a50=(a50*a29);
  a30=(a28*a00);
  a26=(a54*a32);
  a30=(a30-a26);
  a30=(a01*a30);
  a30=(a30*a25);
  a50=(a50+a30);
  a30=(a32*a00);
  a26=(a54*a28);
  a47=(a30+a26);
  a47=(a01*a47);
  a47=(a47*a24);
  a50=(a50+a47);
  a34=(a34*a50);
  a33=(a33*a34);
  a49=(a49+a33);
  a35=(a35*a50);
  a35=(a02*a35);
  a49=(a49+a35);
  if (res[0]!=0) res[0][13]=a49;
  a49=casadi_sign(a03);
  a35=1.1100000000000001e-03;
  a33=(a35*a03);
  a34=1.5000000000000000e+00;
  a34=(a34*a31);
  a31=(a07*a34);
  a47=(a08*a55);
  a31=(a31+a47);
  a47=(a33*a31);
  a47=(a49*a47);
  a36=(a05*a31);
  a36=(a35*a36);
  a47=(a47+a36);
  a36=(a03+a03);
  a46=(a46*a55);
  a56=(a07*a46);
  a36=(a36*a56);
  a47=(a47+a36);
  a36=-3.0249999999999999e-01;
  a36=(a36*a34);
  a57=(a08*a36);
  a58=(a07*a50);
  a57=(a57+a58);
  a30=(a30-a26);
  a30=(a01*a30);
  a30=(a30*a29);
  a32=(a32*a28);
  a54=(a54*a00);
  a32=(a32+a54);
  a32=(a01*a32);
  a32=(a32*a25);
  a30=(a30+a32);
  a00=casadi_sq(a00);
  a09=(a09+a00);
  a01=(a01*a09);
  a52=(a52-a01);
  a52=(a52*a24);
  a30=(a30+a52);
  a52=(a08*a30);
  a57=(a57+a52);
  a04=(a04*a57);
  a49=(a49*a04);
  a47=(a47+a49);
  a49=(a05*a57);
  a49=(a02*a49);
  a47=(a47+a49);
  if (res[0]!=0) res[0][14]=a47;
  a47=(a37+a37);
  a51=(a47*a51);
  a47=(a47*a27);
  a51=(a51+a47);
  a37=casadi_sign(a37);
  a38=(a38*a50);
  a37=(a37*a38);
  a51=(a51+a37);
  a39=(a39*a50);
  a39=(a02*a39);
  a51=(a51+a39);
  if (res[0]!=0) res[0][15]=a51;
  a51=casadi_sign(a10);
  a39=(a35*a10);
  a37=(a14*a34);
  a38=(a15*a55);
  a37=(a37+a38);
  a38=(a39*a37);
  a38=(a51*a38);
  a47=(a12*a37);
  a47=(a35*a47);
  a38=(a38+a47);
  a47=(a10+a10);
  a49=(a14*a46);
  a47=(a47*a49);
  a38=(a38-a47);
  a47=(a14*a50);
  a04=(a15*a36);
  a47=(a47-a04);
  a04=(a15*a30);
  a47=(a47+a04);
  a11=(a11*a47);
  a51=(a51*a11);
  a38=(a38+a51);
  a51=(a12*a47);
  a51=(a02*a51);
  a38=(a38+a51);
  if (res[0]!=0) res[0][16]=a38;
  a38=(a40+a40);
  a35=(a35*a53);
  a53=(a38*a35);
  a38=(a38*a27);
  a53=(a53-a38);
  a40=casadi_sign(a40);
  a41=(a41*a50);
  a40=(a40*a41);
  a53=(a53+a40);
  a42=(a42*a50);
  a42=(a02*a42);
  a53=(a53+a42);
  if (res[0]!=0) res[0][17]=a53;
  a53=casadi_sign(a16);
  a42=(a48*a16);
  a40=(a42*a31);
  a40=(a53*a40);
  a31=(a18*a31);
  a31=(a48*a31);
  a40=(a40+a31);
  a31=(a16+a16);
  a31=(a31*a56);
  a40=(a40+a31);
  a17=(a17*a57);
  a53=(a53*a17);
  a40=(a40+a53);
  a57=(a18*a57);
  a57=(a02*a57);
  a40=(a40+a57);
  if (res[0]!=0) res[0][18]=a40;
  a40=(a43+a43);
  a35=(a40*a35);
  a40=(a40*a27);
  a35=(a35+a40);
  a43=casadi_sign(a43);
  a44=(a44*a50);
  a43=(a43*a44);
  a35=(a35+a43);
  a45=(a45*a50);
  a45=(a02*a45);
  a35=(a35+a45);
  if (res[0]!=0) res[0][19]=a35;
  a35=casadi_sign(a20);
  a45=(a48*a20);
  a43=(a45*a37);
  a43=(a35*a43);
  a37=(a22*a37);
  a48=(a48*a37);
  a43=(a43+a48);
  a48=(a20+a20);
  a48=(a48*a49);
  a43=(a43-a48);
  a21=(a21*a47);
  a35=(a35*a21);
  a43=(a43+a35);
  a47=(a22*a47);
  a02=(a02*a47);
  a43=(a43+a02);
  if (res[0]!=0) res[0][20]=a43;
  a43=(a06+a19);
  a43=(a43*a36);
  a43=(a07*a43);
  a33=(a33*a05);
  a42=(a42*a18);
  a18=(a33+a42);
  a18=(a18*a34);
  a18=(a08*a18);
  a43=(a43-a18);
  a42=(a42*a55);
  a42=(a07*a42);
  a43=(a43+a42);
  a33=(a33*a55);
  a33=(a07*a33);
  a43=(a43+a33);
  a03=casadi_sq(a03);
  a16=casadi_sq(a16);
  a03=(a03+a16);
  a03=(a03*a46);
  a03=(a08*a03);
  a43=(a43-a03);
  a03=(a19*a50);
  a03=(a08*a03);
  a43=(a43-a03);
  a03=(a06*a50);
  a08=(a08*a03);
  a43=(a43-a08);
  a19=(a19*a30);
  a19=(a07*a19);
  a43=(a43+a19);
  a06=(a06*a30);
  a07=(a07*a06);
  a43=(a43+a07);
  if (res[0]!=0) res[0][21]=a43;
  a45=(a45*a22);
  a22=(a45*a55);
  a22=(a14*a22);
  a39=(a39*a12);
  a45=(a39+a45);
  a45=(a45*a34);
  a45=(a15*a45);
  a34=(a13+a23);
  a34=(a34*a36);
  a34=(a14*a34);
  a45=(a45+a34);
  a22=(a22-a45);
  a39=(a39*a55);
  a39=(a14*a39);
  a22=(a22+a39);
  a10=casadi_sq(a10);
  a20=casadi_sq(a20);
  a10=(a10+a20);
  a10=(a10*a46);
  a10=(a15*a10);
  a22=(a22+a10);
  a10=(a23*a50);
  a10=(a15*a10);
  a22=(a22-a10);
  a50=(a13*a50);
  a15=(a15*a50);
  a22=(a22-a15);
  a23=(a23*a30);
  a23=(a14*a23);
  a22=(a22+a23);
  a13=(a13*a30);
  a14=(a14*a13);
  a22=(a22+a14);
  if (res[0]!=0) res[0][22]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void haique_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void haique_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void haique_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void haique_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int haique_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int haique_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real haique_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* haique_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* haique_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* haique_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* haique_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int haique_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
